[package]
name = "wagyu-bitcoin"
version = "0.6.3"
authors = [
    "Collin Chin",
    "Raymond Chu",
    "Ali Mousa",
    "Howard Wu",
    "Todd"
]
description = "A library for generating Bitcoin wallets"
homepage = "https://github.com/AleoHQ/wagyu"
repository = "https://github.com/todcnst1453/wagyu/tree/master/bitcoin"
categories = ["command-line-utilities", "cryptocurrency"]
keywords = ["dogecoin", "blockchain", "cryptocurrency", "no_std", "wallet"]
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
wagyu-model = { path = "../model", version = "0.6.3", default-features = false }

base58 = { version = "0.1" }
bech32 = { version = "0.6.0" }
bitvec = { version = "0.17.4" }
digest = { version = "0.9.0" }
failure = { version = "0.1.8", default-features = false }
hex = { version = "0.4.2", default-features = false }
hmac = { version = "0.7.0" }
libsecp256k1 = { version = "0.3.5", default-features = false, features = ["hmac"] }
pbkdf2 = { version = "0.3.0", features=["parallel"], default-features = false }
rand = { version = "0.7", default-features = false }
rand_xorshift = { version = "0.2" }
ripemd160 = { version = "0.8", default-features = false }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.8", default-features = false }
tiny-keccak = { version = "1.4" }

[features]
default = ["std"]
std = ["wagyu-model/std"]

[badges]
travis-ci = { repository = "AleoHQ/wagyu", branch = "master" }
